---
- include: users.yml
  when: users__enabled | bool

- include: forward.yml
  when: users__enabled | bool

- include: sshkeys.yml
  when: users__enabled | bool

- include: resources.yml
  when: users__enabled | bool

- include: dotfiles.yml
  when: users__enabled | bool
  tags: [ 'role::users:dotfiles' ]
